name: CD
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  buildrelease:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build --configuration Release
      
      - name: Lint
        run: |
          build_path="getcontent/bin/Release/net5.0/"

          cd "$build_path"
          tar -cf release.tar getcontent.exe
          mv release.tar ../../../../
        
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.tar
