name: CI
on: [ pull_request, workflow_dispatch ]

jobs:
  buildandtest:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build
      
      - name: Lint
        run: |
          dotnet tool install -g JetBrains.ReSharper.GlobalTools

          declare -i SUCCESS=0
          declare -i SEVERAL_ERRORS_IN_CSHARP_CODE=1

          logs='logs.log'
          jb inspectcode getcontent.sln -s=warning -o="$logs"
          grep '<Issues />' "$logs" || exit "$SEVERAL_ERRORS_IN_CSHARP_CODE"
          exit "$SUCCESS"
